### ISSUE TITLE
MaticJS example scripts not working, documentation outdated

### ISSUE THREAD

**Issue by sudeepb02** [maticnetwork/matic.js#209]
The example scripts for MaticJS in the /examples directory is outdated. The scripts error out without any actionable message and the documentation for the same is also outdated. 
For example: There is no `balance-of-ERC20.js` file in the examples directory, but it is mentioned in README. Other scripts also don't work even after following the README configuration steps.

**Comment by ujjwalgupta94** [comment]
Ohk thanks for letting us know. We are working on improving docs - We have a PR open for doc update - https://github.com/maticnetwork/matic.js/pull/208/files

We also have plan to create new dedicated doc site. Regarding example - i will update with updated matic.js .

**Comment by sudeepb02** [comment]
Hi @ujjwalgupta94 @fuzious,
Any ETA on when this will be fixed?

**Comment by ujjwalgupta94** [comment]
Hey @sudeepb02 we have just updated the readme. Please check.

**Comment by ujjwalgupta94** [comment]
also when you say example script, you mean `examples` folder or doc codes ?

**Comment by sudeepb02** [comment]
> also when you say example script, you mean code inside `examples` folder or doc codes ?

I tried both, but none of them worked

**Comment by fuzious** [comment]
Hey @sudeepb02 , we will be having a look at the examples folder, meanwhile, if you can share your code and error, maybe we can help you resolve it.

**Comment by sudeepb02** [comment]
> Hey @sudeepb02 , we will be having a look at the examples folder, meanwhile, if you can share your code and error, maybe we can help you resolve it.

Sure, but I need to check if I still have the scripts I wrote while testing

**Comment by ujjwalgupta94** [comment]
@sudeepb02 we have already started working on seperate doc site, @fuzious is also checking the examples code present in examples folder. So timeline wise, we will complete it by mid of this month.

**Comment by ImPedro29** [comment]
i didn't find anything about stake manager, is a missing doc or isn't implemented?

**Comment by ujjwalgupta94** [comment]
Matic.js doesn't contains anything related to staking. it is only for transaction related to  polygon bridge.

For staking part you can find it here - 

https://docs.matic.network/docs/validate/basics/validator/

https://docs.matic.network/docs/validate/validator/staking

**Comment by ujjwalgupta94** [comment]
@sudeepb02 have created the doc site here - https://maticnetwork.github.io/matic.js/ and we have also updated the examples. 

Please let us know if you have any feedback.
